# Setup
title:               Vanessa's notes
tagline:             'About math/some machine learning'

url:                 http://ymvanessa.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vanessa
  email:             ymengvanessa@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
